spring.datasource.url=jdbc:postgresql://${BACK_POSTGRES_HOSTNAME:localhost}:${BACK_POSTGRES_PORT:5432}/${BACK_POSTGRES_BD}
spring.datasource.username=${BACK_POSTGRES_USER}
spring.datasource.password=${BACK_POSTGRES_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


jwt-secret=${JWT_KEY_SECRET}

cerebras.api.key=${CEREBRAS_API_KEY}
cerebras.api.url=https://api.cerebras.ai/v1/chat/completions
cerebras.model=gpt-oss-120b

spring.jpa.defer-datasource-initialization=false
spring.jpa.hibernate.ddl-auto=none
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true