CREATE TABLE area (
                      id_area INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      nome_area VARCHAR(100) NOT NULL UNIQUE
);
CREATE TABLE empresa (
                      id_empresa INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      nome VARCHAR(100) NOT NULL UNIQUE
);
CREATE TABLE instituicao (
                             id_instituicao INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             nome_instituicao VARCHAR(150) NOT NULL UNIQUE
);
CREATE TABLE role (
                      id_role INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name_role VARCHAR(50) NOT NULL UNIQUE
);
CREATE TABLE idioma (
                        id_idioma INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        idioma_nome VARCHAR(100) NOT NULL UNIQUE
);
CREATE TABLE habilidade (
                            id_habilidade INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            nome VARCHAR(100) NOT NULL UNIQUE
);
CREATE TABLE rede_social (
                             id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             nome VARCHAR(100) NOT NULL UNIQUE
);
CREATE TABLE curso (
                       id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       nome_curso VARCHAR(150) NOT NULL UNIQUE
);
CREATE TABLE usuario (
                         id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         nome VARCHAR(150) NOT NULL,
                         email VARCHAR(150) NOT NULL UNIQUE,
                         senha VARCHAR(255) NOT NULL,
                         id_area INTEGER,
                        CONSTRAINT fk_usuario_area FOREIGN KEY (id_area) REFERENCES area(id_area)
);

CREATE TABLE token_usuario (
                       id_token INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       token TEXT NOT NULL,
                       id_usuario INTEGER NOT NULL,
                       CONSTRAINT fk_token_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id)
                           ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE disponibilidade (
                                id_disponibilidade INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                disponibilidade_inicio DATE,
                                modelo_de_trabalho VARCHAR(50),
                                id_usuario INTEGER NOT NULL,
                                CONSTRAINT fk_disponibilidade_usuario FOREIGN KEY (id_usuario) REFERENCES
                                    usuario(id) ON DELETE CASCADE ON UPDATE CASCADE,
                                CONSTRAINT chk_disponibilidade_futura CHECK ( disponibilidade_inicio IS NULL
                                    OR disponibilidade_inicio >= CURRENT_DATE )
);
CREATE TABLE formacao (
                          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          tipo_formacao VARCHAR(100),
                          data_inicio DATE,
                          data_conclusao DATE,
                          em_andamento BOOLEAN DEFAULT FALSE,
                          id_usuario INTEGER NOT NULL,
                          id_curso INTEGER,
                          CONSTRAINT fk_formacao_usuario FOREIGN KEY (id_usuario) REFERENCES
                              usuario(id) ON DELETE CASCADE ON UPDATE CASCADE,
                          CONSTRAINT fk_formacao_curso FOREIGN KEY (id_curso) REFERENCES curso(id) ON
                              DELETE SET NULL ON UPDATE CASCADE,
                          CONSTRAINT chk_formacao_datas CHECK ( data_inicio IS NULL OR data_conclusao
                              IS NULL OR data_inicio <= data_conclusao ),
                          CONSTRAINT chk_formacao_andamento CHECK ( NOT (em_andamento = TRUE AND
                                                                         data_conclusao IS NOT NULL) )
);
CREATE TABLE experiencia (
                             id_experiencia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             titulo VARCHAR(150),
                             cargo VARCHAR(150),
                             descricao TEXT,
                             data_inicio DATE,
                             data_fim DATE,
                             trabalho_atual BOOLEAN DEFAULT FALSE,
                             id_usuario INTEGER NOT NULL,
                             id_area INTEGER,
                             id_empresa INTEGER,
                             CONSTRAINT fk_experiencia_usuario FOREIGN KEY (id_usuario) REFERENCES
    usuario(id) ON DELETE CASCADE ON UPDATE CASCADE,
                             CONSTRAINT fk_experiencia_empresa FOREIGN KEY (id_empresa) REFERENCES
                                 empresa(id_empresa),
    CONSTRAINT fk_experiencia_area FOREIGN KEY (id_area) REFERENCES area(id_area) ON
        DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT chk_experiencia_datas CHECK ( data_inicio IS NULL OR data_fim IS
        NULL OR data_inicio <= data_fim ),
    CONSTRAINT chk_experiencia_atual CHECK ( NOT (trabalho_atual = TRUE AND
                                                  data_fim IS NOT NULL) )
    );
CREATE TABLE certificacao (
                              id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              nome_certificacao VARCHAR(150),
                              data_conclusao DATE,
                              em_andamento BOOLEAN DEFAULT FALSE,
                              certificado BYTEA,
                              id_usuario INTEGER NOT NULL,
                              id_instituicao INTEGER NOT NULL,
                              CONSTRAINT fk_certificacao_usuario FOREIGN KEY (id_usuario) REFERENCES
                                  usuario(id) ON DELETE CASCADE ON UPDATE CASCADE,
                              CONSTRAINT fk_certificacao_instituicao FOREIGN KEY (id_instituicao)
                                  REFERENCES instituicao(id_instituicao) ON DELETE RESTRICT ON UPDATE CASCADE,
                              CONSTRAINT chk_certificacao_andamento CHECK ( NOT (em_andamento = TRUE AND
                                                                                 data_conclusao IS NOT NULL) )
);
CREATE TABLE projeto (
                         id_projeto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         titulo VARCHAR(150),
                         descricao TEXT,
                         link_repositorio VARCHAR(255),
                         id_usuario INTEGER NOT NULL,
                         CONSTRAINT fk_projeto_usuario FOREIGN KEY (id_usuario) REFERENCES
                             usuario(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE usuario_idioma (
                                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                id_usuario INTEGER NOT NULL,
                                id_idioma INTEGER NOT NULL,
                                nivel VARCHAR(50),
                                CONSTRAINT uq_usuario_idioma UNIQUE(id_usuario, id_idioma),
                                CONSTRAINT fk_usuario_idioma_usuario FOREIGN KEY (id_usuario) REFERENCES
                                    usuario(id) ON DELETE CASCADE ON UPDATE CASCADE,
                                CONSTRAINT fk_usuario_idioma_idioma FOREIGN KEY (id_idioma) REFERENCES
                                    idioma(id_idioma) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE role_user (
                              id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              id_usuario INTEGER NOT NULL,
                              id_role INTEGER NOT NULL,
                              CONSTRAINT uq_usuario_role UNIQUE(id_usuario, id_role),
                              CONSTRAINT fk_usuario_role_usuario FOREIGN KEY (id_usuario) REFERENCES
                                  usuario(id) ON DELETE CASCADE ON UPDATE CASCADE,
                              CONSTRAINT fk_usuario_role_role FOREIGN KEY (id_role) REFERENCES role(id_role) ON
                                  DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE usuario_habilidade (
                                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    id_usuario INTEGER NOT NULL,
                                    id_habilidade INTEGER NOT NULL,
                                    CONSTRAINT uq_usuario_habilidade UNIQUE(id_usuario, id_habilidade),
                                    CONSTRAINT fk_usuario_habilidade_usuario FOREIGN KEY (id_usuario) REFERENCES
                                        usuario(id) ON DELETE CASCADE ON UPDATE CASCADE,
                                    CONSTRAINT fk_usuario_habilidade_habilidade FOREIGN KEY (id_habilidade)
                                        REFERENCES habilidade(id_habilidade) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE usuario_rede_social (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     id_usuario INTEGER NOT NULL,
                                     id_rede_social INTEGER NOT NULL,
                                     link VARCHAR(255),
                                     CONSTRAINT uq_usuario_rede_social UNIQUE(id_usuario, id_rede_social),
                                     CONSTRAINT fk_usuario_rede_social_usuario FOREIGN KEY (id_usuario)
                                         REFERENCES usuario(id) ON DELETE CASCADE ON UPDATE CASCADE,
                                     CONSTRAINT fk_usuario_rede_social_rede FOREIGN KEY (id_rede_social)
                                         REFERENCES rede_social(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE curriculo_usuario (
                                   id_curriculo       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   titulo             VARCHAR(255),
                                   data_criacao       TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
                                   ultima_atualizacao TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
                                   curriculo          BINARY VARYING NOT NULL,
                                   id_usuario         INTEGER NOT NULL,

                                   CONSTRAINT fk_curriculo_usuario
                                       FOREIGN KEY (id_usuario)
                                           REFERENCES usuario(id)
);