CREATE TABLE curriculo_gerado (
                                  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  pdf          BINARY LARGE OBJECT,
                                  data_geracao TIMESTAMP NOT NULL,
                                  id_usuario   BIGINT NOT NULL,
                                  CONSTRAINT fk_curriculo_gerado_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id)
);